app.view("<head>")
app.view("<meta charset="UTF-8">")
app.view("<meta name="viewport" content="width=device-width, initial-scale=1.0">")
app.view("<script src="function.js"></script>")
app.view("</head>")
